version: '3.7'
networks:
  udemy:
    driver: bridge
services:
    udemyapp:
      image: webdevops/php-nginx:7.4-alpine
      container_name: laravelnginxc
      restart: no
      ports:
        - 8000:80
      volumes:
      - ./src:/laravel
      environment:
        WEB_DOCUMENT_ROOT: /laravel/public
      hostname: apphost
      networks:
      - udemy
    db:
      image: mariadb:11.1.2
      container_name: udemydbc
      restart: unless-stopped
      environment:
        MARIADB_DATABASE: ${MARIADB_DATABASE}
        MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        SERVICE_TAG: dev 
        SERVICE_NAME: mariadb
      hostname: dbhost
      ports:
        - 3307:3306
      volumes:
        - ./docker-compose/sql:/docker-entrypoint-initdb.d
      networks:
      - udemy
      
